// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixciomcduejqjbruobfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4Y2lvbWNkdWVqcWpicnVvYmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzQ0MzEsImV4cCI6MjA2NzM1MDQzMX0.4oDQkwiDVt5Hrl9lqHz3SvjSM_CfTtSY4dvSFHQ9TCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});